version: "3.8"

services:
  webfrontend:
    image: vova186/kuber-ui
    container_name: webfrontend
    ports: 
      - "4200:80"
    depends_on:
      - webapi
    #network_mode: bridge
    # networks:
    #   - web

  webapi:
    image: vova186/kuber-proxy
    container_name: webapi
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "7000:80"
    #network_mode: bridge
    # networks:
    #   - web

# networks:
#   web:
#     name: bridge
    #external: true