version: "3.8"

services:
  webfrontend:
    image: vova186/kuber-ui
    ports: 
      - "4200:80"
    networks:
      - app-network

  webapi:
    image: vova186/kuber-proxy
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "7000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge